live_diy/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'
  resources :categories do
    resources :projects
  end
end

live_diy/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

live_diy/app/models/category.rb
class Category < ApplicationRecord
  has_many :projects

  validates :image_url, presence: true
  

end

live_diy/app/models/project.rb
class Project < ApplicationRecord
  belongs_to :category
end

live_diy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

live_diy/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    render :json => @categories
  end

  def show
    @category = Category.find(params[:id])
    render :json => @category    
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save(category_params)
      flash[:notice] = "The category #{@category.name} has successfully been created."
      redirect_to @category
      render json: {success: true}, status: :ok
    else
      @category.errors.full_messages
      flash.now[:notice] = "Must apply an image to create category.  Come on now!"
      render :new
    end
  end



  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to @category
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to @category
  end

  private

  def category_params
    params.require(:category).permit(:name, :image_url)
  end

end

live_diy/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
    @category = @project.category
  end

  def new
    @category = Category.find(params[:category_id])
    @project = Project.new
  end

  def create
    @category = Category.find(params[:category_id])
    @project = @category.projects.create!(project_params)
    redirect_to @category
  end

  def edit
    @category = Category.find(params[:category_id])
    @project = Project.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @category.projects.update(project_params)
    redirect_to @category
  end

  def destroy
    @category = Category.find(params[:category_id])
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to @category
  end

  private

  def project_params
    params.require(:project).permit(:name, :image_url, :instructions)
  end

end

live_diy/app/helpers/application_helper.rb
module ApplicationHelper
end

live_diy/app/helpers/categories_helper.rb
module CategoriesHelper
end

live_diy/app/helpers/category_helper.rb
module CategoryHelper
end

live_diy/app/helpers/project_helper.rb
module ProjectHelper
end

live_diy/app/helpers/projects_helper.rb
module ProjectsHelper
end

live_diy/app/helpers/welcome_helper.rb
module WelcomeHelper
end

live_diy/app/views/categories/_form.html.erb
  <%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

<%= f.submit %>
<% end %>

live_diy/app/views/categories/edit.html.erb
<%= render 'form' %>
<p><%= link_to "(-) Remove Category", category_path(@category),
        method: :delete,
        data: {confirm: "Are you sure?"} %>
</p>

live_diy/app/views/categories/index.html.erb
<% flash.each do |type, message| %>
  <p><% type %><%= message %></p>
<% end %>

<br>
<br>

<p class='add'><%= link_to "(+) Add Category", new_category_path(@category) %></p>

<% @categories.each do |category| %>
  <ul class='category'><li><%= image_tag category.image_url %></li>
  <li><%= link_to category.name, category_path(category) %>  <%= link_to "  (Edit)", edit_category_path(category) %></li></ul>
<% end %>

live_diy/app/views/categories/new.html.erb
<%= render 'form' %>

<% flash.each do |type, message| %>
  <p><% type %><%= message %></p>
<% end %>

live_diy/app/views/categories/show.html.erb
<h1><%= @category.name %> DIY projects</h1>

<%= link_to "(+) Add New Project", new_category_project_path(@category) %>


<% @category.projects.each do |project| %>
  <p><%= link_to project.name, category_project_path(@category, project) %>  <%= link_to "(edit)", edit_category_project_path(@category, project) %></p>
<% end %>

live_diy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>LiveDiy</title>
  </head>
  <header><h1><%= link_to "Live DIY", categories_path %></h1></header>
  <br>
  <body>
    <%= yield %>
  </body>
</html>

live_diy/app/views/projects/_form.html.erb
<%= form_for [@category, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.label :time_to_completion %>
  <%= f.text_field :time_to_completion %>

  <%= f.label :instructions %>
  <%= f.text_area :instructions %>

<%= f.submit %>
<% end %>

live_diy/app/views/projects/edit.html.erb
<%= render 'form' %>

<%= link_to "(delete)", category_project_path(@category, @project),
    method: :delete,
    data: {confirm: "What! Why? Are you sure?"} %>

live_diy/app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>Find me in app/views/projects/index.html.erb</p>

live_diy/app/views/projects/new.html.erb
<%= form_for [@category, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.label :time_to_completion %>
  <%= f.text_field :time_to_completion %>

  <%= f.label :instructions %>
  <%= f.text_area :instructions %>

<%= f.submit %>
<% end %>

live_diy/app/views/projects/show.html.erb
<h3><%= @project.name %></h3>
<p><%= image_tag @project.image_url %></p>
<p><%= @project.instructions %></p>